# Generated by Django 4.1.3 on 2022-11-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='age',
            field=models.IntegerField(),
        ),
    ]
